# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'fake-netease-music' do

# use_frameworks!
    pod 'MJRefresh'
    pod 'YYModel'
    pod 'ZXPAutoLayout'
    pod 'EmptyDataKit'
    pod 'BlocksKit'
    pod 'YYWebImage'
    pod 'WMPageController'
    pod 'MBProgressHUD'
end
